name: Patuxmix
version: '${version}'
main: com.mixay.patuxmix.Patuxmix
api-version: '1.16'
depend: [NBTAPI]
commands:
  getshovel:
    description: Get netherite shovel command
  getpearl:
    description: Get unique TP perl command

